#! /bin/sh
# /etc/init.d/pi_lcd 

### BEGIN INIT INFO
# Provides:          pi_lcd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting pi_lcd"
    # run application you want to start
    /home/pi/workspace/pi_lcd/pi_lcd_with_button.py
    ;;
  stop)
    echo "Stopping pi_lcd"
    # kill application you want to stop
    killall pi_lcd_with_button.py
    ;;
  *)
    echo "Usage: /etc/init.d/pi_lcd {start|stop}"
    exit 1
    ;;
esac

exit 0:1
